GET http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaSIsImlkIjoiNjU1NTczMDBiZWNjYjY1MjIxMTIzOTYwIiwiaWF0IjoxNzAwMjUyMjk3fQ.rC3kx6jdUlkKjgvtmlqg792mc29SxbjqqsB3f9MbuBo

###

GET http://localhost:3003/api/users HTTP/1.1

###

POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "quad",
  "password": "1234567"
}

###

POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "tri",
  "password": "1234567"
}

###

DELETE http://localhost:3003/api/blogs/6557bc95336937c65f51039c HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaSIsImlkIjoiNjU1NTczMDBiZWNjYjY1MjIxMTIzOTYwIiwiaWF0IjoxNzAwMjQ2NDg3fQ.5b3hjfsT9DlpPcQrYfoP54G5WIJuNfyZuymWgkHpD6A

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaSIsImlkIjoiNjU1NTczMDBiZWNjYjY1MjIxMTIzOTYwIiwiaWF0IjoxNzAwMjQ2NDg3fQ.5b3hjfsT9DlpPcQrYfoP54G5WIJuNfyZuymWgkHpD6A

{
  "title": "Title_Blog 1",
  "author": "Author_Blog 1",
  "url": "www.blog1.com",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaSIsImlkIjoiNjU1NTczMDBiZWNjYjY1MjIxMTIzOTYwIiwiaWF0IjoxNzAwMjQ2NDg3fQ.5b3hjfsT9DlpPcQrYfoP54G5WIJuNfyZuymWgkHpD6A

{
  "title": "Title_Blog 2",
  "author": "Author_Blog 2",
  "url": "www.blog2.com",
  "likes": 2
}

###
PUT http://localhost:3003/api/blogs/655f0e5b9b7c0623957d60aa/comments HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaSIsImlkIjoiNjU1NTczMDBiZWNjYjY1MjIxMTIzOTYwIiwiaWF0IjoxNzAwMjQ2NDg3fQ.5b3hjfsT9DlpPcQrYfoP54G5WIJuNfyZuymWgkHpD6A

{
  "comment": "This is testing comment 4"
}


###
POST http://localhost:3003/api/blogs/update-schema HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaSIsImlkIjoiNjU1NTczMDBiZWNjYjY1MjIxMTIzOTYwIiwiaWF0IjoxNzAwMjQ2NDg3fQ.5b3hjfsT9DlpPcQrYfoP54G5WIJuNfyZuymWgkHpD6A
